### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Gorian** [pheinrichs/myLibreNMS#1]
It'd be helpful if your description in the app page listed the requirements, if any, to use the app with your server. I.E. do you require any open ports besides 80?

**Comment by murrant** [comment]
Please port 443. :D

**Comment by florianbeer** [comment]
My LibreNMS installation is also only reachable via port 443 (TLS) and thus no graphs are being loaded, although all other API requests seem to work perfectly fine. It would be great if you could allow for this configuration.

Thanks for your amazing work this is a really great addition to my monitoring toolset!

**Comment by pheinrichs** [comment]
@florianbeer hmm, TLS shouldn't be an issue, right now the graphs do only display if your librenms instance is exporting the graphs as PNG. Is that the case? Or are they set to SVG. If so I am working on getting that to work so hopefully soon :)

**Comment by florianbeer** [comment]
They are set to PNG, I specifically checked that.  
Whenever I go to any view that has graphs, I only get the spinning loading icon and nothing else happens.

Is there anything else I can check to help in the debugging effort?

**Comment by pheinrichs** [comment]
@florianbeer sorry for the delay, had jury duty :+1:  I'm trying to see if i've replicated it, do you see the api request in your logs/access_log in your librenms instance, and what status code it's returning?

**Comment by florianbeer** [comment]
No worries, there's no rush.  
I will check access logs tonight and see if I can find anything useful and post here.

Thanks!

**Comment by florianbeer** [comment]
Sorry, it took some more time but now I have a log-line for you (`/var/log/apache2/error.log`):

```
Mar 11 13:45:56 dionysos apache2[32094]: [error] [client 80.108.xxx.xxx] FastCGI: comm with server "/usr/lib/cgi-bin/php5-fcgi" aborted: error parsing headers: malformed header ':'
```
using php5-fpm 5.6  on Apache 2.2

Do you have any idea how I can get a more meaningful error message/debug log?  
To me this seems like it could rather be an issue with my LibreNMS install or webserver config and not with your app at all. Using LibreNMS via browser doesn't yield those error logs though.

**Comment by florianbeer** [comment]
Seems like librenms/librenms/pull/6186 fixed the issue.

Are you by any chance running LibreNMS on another webserver than me and that's why the bug didn't manifest itself?

**Comment by pheinrichs** [comment]
@florianbeer Awesome to hear! Not sure why it affected you, I have mine running on apache on centos. Curious that it wasn't getting the headers.

**Comment by florianbeer** [comment]
Hmm, must be something different between our two webserver configurations. Anyway, it's all working now :)

Thanks again for your work on this app, I like it very much!
