### ISSUE TITLE
Android - Cannot open connected server

### ISSUE THREAD

**Issue by DerDanilo** [pheinrichs/myLibreNMS#10]
For some reason I cannot open the connected server.
This worked fine before with another server, but right now it does not anymore.

Android 7 - Samsung Galaxy S6
Android App 1.1.5
URL: https://monitor. ..... .de

Does the app have an issue with "monitor" in the url?

When I tab the server in the list nothing happens. 

Can you fix this?

**Comment by pheinrichs** [comment]
Hmm,  monitor shouldn't be an issue.
Is by any chance your cert self signed? 

I had to do some adjustments in android studio and may have forgotten to add the info for self signed.

**Comment by DerDanilo** [comment]
Let's Encrypt, Multi-Domain Cert. Monitor. is an alternative subdomain name, not main.
If this is the issue it should be fixable, multi domain certs are quiet commond these days. 

Thanks!

**Comment by pheinrichs** [comment]
Just did some testing certificates shouldn't be an issue. 

You mentioned this worked fine with another server? Have you ever successfully connected the mylibrenms app to this current server?

Just for sake of testing, would you be able to attempt adding the demo server on the app and see if that works?

url: https://demo.librenms.org
api token: a765d19f9ebcdd3632f2ecd92330b7f6

**Comment by DerDanilo** [comment]
Demo server works fine. Thanks

The security settings for nginx and ssl are very strict, could that be an 
issue?


Btw, all connected Servers are lost when there is an app update installed.

Viele Grüße
---
Danilo Schwabe
Schwabe EDV
Einfach. Schnell. Persönlich.

danilo@schwabe-edv.de
www.schwabe-edv.de




Am 2. August 2017 14:16:46 schrieb Paul Heinrichs <notifications@github.com>:

**Comment by pheinrichs** [comment]
Noted, I've been meaning to implement a different storage method, thanks.

The nginx could potentially be an issue. 
What method of authentication are you using?

Try testing the API of your server with a curl request and see what the response is.

curl -H 'X-Auth-Token: YOURAPITOKENHERE' https://monitor....de/api/v0

**Comment by DerDanilo** [comment]
Here we go:

```
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

My nginx config contains:
```
ssl_certificate /etc/nginx/ssl/LE.crt;
ssl_certificate_key /etc/nginx/ssl/LE.key;
## verify chain of trust of OCSP response using Root CA and Intermediate certs
ssl_trusted_certificate /etc/nginx/ssl/LEfullchain.pem;
```

The domain name used for LibreNMS is an alternative cert name.
Still I don't understand why there is an issue here. Several browsers don't have any issue.

**Comment by pheinrichs** [comment]
As for certs, i can't say for certain. I haven't used let's encrypt personally so i can't speak to much to that. Maybe ask around in the librenms irc for some help to see why that is?

On building the error message,
That's a great idea, i'll see what i can come up with to make this a little more informative. Thanks for the input.

**Comment by DerDanilo** [comment]
I fixed the chain issue. That seems not to be the issue anymore. The Android Browser shows the webpage properly without a problem now.

* Curl connection from remote server works fine now.
* Local curl connection runs into the following:
```
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
```

**Comment by pheinrichs** [comment]
Great to hear, 
I'll add error messages on login to my list of things to do for the next update.

Thanks for the input!
