### ISSUE TITLE
Display sysname instead of IP?

### ISSUE THREAD

**Issue by twelch24** [pheinrichs/myLibreNMS#13]
Can this display the sysname or something other than device IP address for the device list?

**Comment by pheinrichs** [comment]
Sounds like a plan, i'll see if I can push this out this week.

**Comment by pheinrichs** [comment]
So I've added this similar to LibreNMS where the hostName/IP address is still the primary text but the sysname is the subtext for that device. 
Is this kind of what you were thinking?

**Comment by twelch24** [comment]
That's probably what I mean. I was looking for something similar to the way $config['force_ip_to_sysname'] = true; works with the maps.

Awesome response time.
