### ISSUE TITLE
Unable to Reach Server

### ISSUE THREAD

**Issue by jodell22** [pheinrichs/myLibreNMS#5]
Keep getting an "unable to reach server" error.

I can log into the server via the web from my device, but can't login via the app. I have generated an API token in the server.

I did set up a self signed openssl cert for this server, and have HTTP redirecting to HTTPS to prevent people from being able to login via HTTP. Not sure if the self signed cert is what is causing issues?

**Comment by pheinrichs** [comment]
So the URL in the login screen is "https://etc.librenms"? As long as port 443 is open to the network it should be fine, i'll double check this and give my server a self signed cert and see if it works for me.

**Comment by pheinrichs** [comment]
@jodell22 I was able to recreate this, yeah seems like it doesn't like the self signed cert. I'm just about ready to push another update, i'll throw this in to allow any certs.

**Comment by jodell22** [comment]
Awesome, thanks for the quick response!

**Comment by pheinrichs** [comment]
@jodell22 update just released. Give it a shot and let me know if that works for you.

**Comment by laf** [comment]
<3 @pheinrichs  :)

**Comment by laf** [comment]
@jodell22 Has the update fixed your issue?

**Comment by jodell22** [comment]
Yes it fixed my issue. I had some other settings that had disabled everything other than LDAP authentication which was also preventing me from using the API to authenticate, but I was able to test and verify that this is fixed on a new install. Thanks!
