### ISSUE TITLE
QR Code Reader Broken/Saved Sites Deleted

### ISSUE THREAD

**Issue by tracerrx** [pheinrichs/myLibreNMS#7]
Most recent version for iPhone has broken ability to scan QR codes for api tokens.

This version also deleted my prev saved Sites.

**Comment by pheinrichs** [comment]
Thanks, I was working on that this evening. I noticed the data didn't transition over for some reason so I was debugging that! I'll post a fix for the QR asap too!

**Comment by pheinrichs** [comment]
Submitting the IPA, update should be live shortly. Thanks for the issue report!

**Comment by tracerrx** [comment]
Thanks for quick fix, will test it once it's through the app store process

**Comment by pheinrichs** [comment]
Version is live, let me know if that fixes it for you.

**Comment by tracerrx** [comment]
That worked! QR Code fixed && Didn't blank out my prev saves.
