### ISSUE TITLE
Issue with self signed certs

### ISSUE THREAD

**Issue by dersini** [pheinrichs/myLibreNMS#8]
I ran into an issue with self signed cert. Importing the cert solved it. How about a prompt that would give user an option to connect to the server with self signed cert?

Thanks.

**Comment by pheinrichs** [comment]
Is this for android or iOS?

**Comment by dersini** [comment]
Actually both. Android works after importing the cert. I haven't tested
importing on ios, though I am guessing it would work as well.

**Comment by pheinrichs** [comment]
I've got a commit ready for android so I'll push this to both stores tomorrow! Thanks

**Comment by dersini** [comment]
Awesome!
Thanks.

**Comment by pheinrichs** [comment]
Android should be releasing shortly, and iOS should be within a couple days.

**Comment by dersini** [comment]
Android works now.

**Comment by pheinrichs** [comment]
@dersini iOS app is live, just wanted to make sure this is working now also.

**Comment by dersini** [comment]
It is working. Thanks for the fix.

**Comment by laf** [comment]
@dersini Thanks for reporting back, feel free to close this issue :)

**Comment by dersini** [comment]
No problem. BTW, is this an open source project?

**Comment by laf** [comment]
The mobile apps aren't at present no, obviously LibreNMS itself is.

**Comment by dersini** [comment]
Got it.
