### ISSUE TITLE
Syslog messages

### ISSUE THREAD

**Issue by qutschwalze** [pheinrichs/myLibreNMS#9]
Please add Syslog messages to the mobile app.

**Comment by pheinrichs** [comment]
Gladly, I'll just review the API docs for librenms to see if it's available. If not I'll open an issue in there to get it started.

**Comment by pheinrichs** [comment]
Issue has been opened, please see librenms/librenms#6949 for updates on API status updates.

**Comment by pheinrichs** [comment]
This has been submitted to both apple and android and hopefully should be live shortly!
